apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort                # Make it accessible outside the cluster
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: https
      port: 443                 # Cluster port
      targetPort: 443           # Pod port
      nodePort: 30080           # Port to access on localhost / node

